import chalk from "chalk";

export default {
  generateApi: `Generated ${chalk.cyan("api.ts")}`,
  generateServicesMetadata: `Generated ${chalk.cyan("services-metadata.ts")}\n`,
  spinner: "Generating TypeScript query abstractions...",
  success: chalk.green("Query abstractions generated successfully\n"),
  failure: chalk.red("Query abstractions generation failed"),
  generated: (fileName: string) => `Generated ${chalk.cyan(fileName)}`,
  generatedIndexFile: `Generated ${chalk.cyan("query-abstractions/index.ts")}\n`,
  notArrayError: (type: string) =>
    `SERVICES_METADATA is not an array. Got: ${type}`,
  generateFailure: "Failed to generate query abstractions:",
  templates: {
    autoGeneratedComment: "// Auto-generated React Query options\n\n",
    serviceComment: (serviceName: string) =>
      `// ${serviceName} query and mutation options\n`,
    exportStatement: (fileName: string) => `export * from "./${fileName}";\n\n`,
  },
};
