import "dotenv/config";
import * as path from "node:path";
import * as fs from "node:fs";
import * as os from "node:os";
import { Eta } from "eta";
import { build } from "esbuild";

import content from "./content.js";

async function loadServicesMetadata(filePath: string) {
  const tempDir = path.join(os.tmpdir(), "ts-loader");
  const tempFile = path.join(tempDir, "temp.mjs");

  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
  }

  await build({
    entryPoints: [filePath],
    outfile: tempFile,
    format: "esm",
    platform: "node",
    bundle: false,
  });

  const module = await import(`file://${tempFile}`);
  return module;
}

const templatesDir = path.resolve(process.cwd(), "./src/templates");

const eta = new Eta();

eta.configure({
  views: templatesDir,
  cache: false,
});

function generateQueryAbstractionsIndex(configs: any[]): string {
  let indexContent = content.templates.autoGeneratedComment;

  for (const service of configs) {
    const fileName = service.name.toLowerCase();
    indexContent += content.templates.serviceComment(service.name);
    indexContent += content.templates.exportStatement(fileName);
  }

  return indexContent;
}

function getImportTypes(routes: any[]): string[] {
  const types = new Set<string>();

  for (const route of routes) {
    if (route.requestBodyType) types.add(route.requestBodyType);
    if (route.requestParamsType) types.add(route.requestParamsType);
  }

  return Array.from(types).filter(Boolean) as string[];
}

async function generateQueryAbstractionsTwo(
  SERVICES_METADATA: any[],
  outputDir: string,
): Promise<void> {
  const queryAbstractionsDir = path.resolve(outputDir, "./query-abstractions");

  if (!fs.existsSync(queryAbstractionsDir)) {
    fs.mkdirSync(queryAbstractionsDir, { recursive: true });
  }

  for (const service of SERVICES_METADATA) {
    const importTypes = getImportTypes(service.routes);
    const queryAbstractionContent = eta.render("query-abstractions.eta", {
      ...service,
      importTypes,
    });
    const fileName = `${service.name.toLowerCase()}.ts`;
    fs.writeFileSync(
      path.resolve(queryAbstractionsDir, fileName),
      queryAbstractionContent,
    );
    console.log(content.generated(fileName));
  }

  const queryAbstractionsIndexContent =
    generateQueryAbstractionsIndex(SERVICES_METADATA);
  fs.writeFileSync(
    path.resolve(queryAbstractionsDir, "index.ts"),
    queryAbstractionsIndexContent,
  );
  console.log(content.generatedIndexFile);
}

async function generateQueryAbstractions(outputDir: string): Promise<void> {
  try {
    const servicesMetadataPath = path.resolve(
      outputDir,
      "./services-metadata.ts",
    );

    const module = await loadServicesMetadata(servicesMetadataPath);
    const SERVICES_METADATA = module.SERVICES_METADATA;

    if (!Array.isArray(SERVICES_METADATA)) {
      throw new Error(content.notArrayError(typeof SERVICES_METADATA));
    }

    await generateQueryAbstractionsTwo(SERVICES_METADATA, outputDir);
  } catch (error) {
    console.error(content.generateFailure, error);
    throw error;
  }
}

export { generateQueryAbstractions };
